name: studywithcharles
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS-style widgets
  cupertino_icons: ^1.0.8

  # Supabase for your Postgres backend
  supabase_flutter: ^2.9.1

  # Environment variable support
  flutter_dotenv: ^5.2.1

  # Firebase core & auth
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
