name: studywithcharles
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Supabase
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2

  # Audio playback
  audioplayers: ^6.5.0

  # Core functionality
  uuid: ^3.0.6
  file_picker: ^10.2.1
  image_picker: ^0.8.7+4

  # ✨ Downgrade http to 0.13.x to resolve conflict
  http: ^0.13.6

  table_calendar: ^3.0.8
  intl: ^0.17.0
  webview_flutter: ^4.10.0
  path_provider: ^2.0.14
  permission_handler: ^12.0.1
  share_plus: ^11.0.0
  firebase_messaging: ^15.2.10
  url_launcher: ^6.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  # Recommended lints
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  
  # For iOS and older Android, we can use your main background image
  image_path: "assets/icon/background.png" 
  
  # For modern Android's adaptive icon
  adaptive_icon_background: "assets/icon/background.png" # Your space image
  adaptive_icon_foreground: "assets/icon/foreground.png" # Your NEW logo image
